# Generated by Django 5.1.4 on 2024-12-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='books',
            name='score',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
